name: Python application

on:
  schedule:
    - cron: '10 * * * *'

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Settings
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          python -m pip install --upgrade pip
          pip install flake8 pytest
          export PATH=$PATH:/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages:/home/runner/.local/lib/python3.10/site-packages

      - name: Action
        env:
          TokisenCalendar: ${{ secrets.TokisenCalendar }}
        run: |
          python TVandRadio.py
